name: Build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - name: Install dependencies and npm packages
        run: |
          sudo apt-get -y install autoconf pkg-config build-essential libglu1 libxi6 libgconf-2-4
          npm install
      - name: Run npm build
        run: |
          npm run build
      - name: Run npm deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm run deploy
      - name: Set AWS caching
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          chmod +x ./set-cache.sh
          ./set-cache.sh
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://michaelgreenhill.net/'
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
